add_newline = true

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold green)'

[username]
style_user = 'yellow bold'
style_root = 'red bold'
format = '[$user]($style) in '
disabled = false
show_always = true

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "purple bold"

[directory]
style = "cyan bold"
read_only = " "
truncation_length = 4
truncate_to_repo = true

[package]
disabled = true
